#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 160
#define SCREEN_HEIGHT 144
#define SCREEN_SCALE 4

#define MAPS_FOLDER "data/maps/"
#define BLOCKSETS_FOLDER "data/bst"
//#define DEBUG
#define TILE_SIZE 8
#define BLOCK_SIZE (TILE_SIZE * 2)
#define METABLOCK_SIZE (BLOCK_SIZE * 2)
#define SCREEN_BLOCKS_W ((SCREEN_WIDTH  + METABLOCK_SIZE - 1) / METABLOCK_SIZE)
#define SCREEN_BLOCKS_H ((SCREEN_HEIGHT + METABLOCK_SIZE - 1) / METABLOCK_SIZE)

#define CAM_OFFSET_X ((SCREEN_WIDTH  / 2) - TILE_SIZE)
#define CAM_OFFSET_Y ((SCREEN_HEIGHT / 2) - TILE_SIZE)

#endif
